dbt_gcp:
  target: dev
  outputs:
    dev:
      method: oauth
      type: bigquery
      
      project: "{{ env_var('PROJECT_ID', 'jcdeah-009') }}"
      dataset: "{{ env_var('BQ_DATASET_RAW', 'cp3_gatot_dataset_raw') }}"
      location: "{{ env_var('REGION', 'asia-southeast2') }}"
      
      threads: 4
      priority: interactive
      job_execution_timeout_seconds: 300
      job_retries: 1