sources:
  - name: raw
    description: Raw data trips
    database: "{{ env_var('PROJECT_ID') }}"
    dataset: "{{ env_var('BQ_DATASET_RAW') }}"
    tables:
      - name: raw_green_taxi
        description: Raw taxi trips.
      - name: raw_zone_taxi
        description: Raw taxi zone.